### PR TITLE
Branch fix check style

### LINKED ISSUE #137: Created json storage for problem report
Created json storage for problem report

### PR DESCRIPTION
**Pull request by richardcom**
Branch fix check style
Fix #137

### CODE REVIEW

**Comment by HCY123902** [comment]
LGTM

**Review by HCY123902 — COMMENTED** [review]
LGTM

**Comment by HCY123902** [comment]
LGTM

File: src/main/java/seedu/address/model/ModelManager.java [hunk 1]
```diff
@@ -141,6 +139,16 @@ public void updateFilteredBookList(Predicate<Book> predicate, Mode mode) {
         filteredBooks.setPredicate(predicate);
     }
 
+    /**
+     * Updates the book list with the predicate.
+     *
+     * @param predicate The predicate that is used to update the list.
+     */
+    public void updateFilteredBookList(Predicate<Book> predicate) {
```
Comment (HCY123902) [inline src/main/java/seedu/address/model/ModelManager.java:147]: LGTM. The defensiveness seems to be present.

File: src/main/java/seedu/address/model/problem/ProblemList.java [hunk 2]
```diff
@@ -25,6 +25,26 @@ public boolean contains(Problem toCheck) {
         return list.stream().anyMatch(toCheck::isSameProblem);
     }
 
+    /**
+     * Replaces the problem {@code target} in the list with {@code editedBook}.
+     * {@code target} must exist in the list.
+     * The book identity of {@code editedBook} must not be the same as another existing book in the list.
+     */
+    public void setProblem(Problem target, Problem editedProblem) {
```
Comment (HCY123902) [inline src/main/java/seedu/address/model/problem/ProblemList.java:33]: LGTM. Interesting usage of set method.

File: src/test/java/seedu/address/model/LibraryTest.java [hunk 3]
```diff
@@ -97,6 +85,11 @@ public void getBookList_modifyList_throwsUnsupportedOperationException() {
         public ObservableList<Book> getBookList() {
             return books;
         }
+
+        @Override
+        public ObservableList<Problem> getProblemList() {
```
Comment (HCY123902) [inline src/test/java/seedu/address/model/LibraryTest.java:90]: LGTM

File: src/main/java/seedu/address/model/Library.java [hunk 4]
```diff
@@ -69,6 +62,16 @@ public void setProblems(List<Problem> problems) {
         this.problems.setProblems(problems);
     }
 
+    /**
+     * Replaces the given book {@code target} in the list with {@code editedBook}.
+     * {@code target} must exist in the library.
+     * The book identity of {@code editedBook} must not be the same as another existing book in the library.
+     */
```
Comment (HCY123902) [inline src/main/java/seedu/address/model/Library.java:69]: LGTM. The concept of defensiveness and abstraction seems to be present.

**Review by HCY123902 — COMMENTED** [review]
LGTM
